spring:
  application:
    name: 'dji-trade-data'

  data:
    mongodb:
      host: mongoDB
      port: 27017
      database: tradeData


  task:
    pool:
      core-size: 2
      max-size: 4
      queue-capacity: 500

version: 1.3

springdoc:
  swagger-ui:
    use-root-path: true